language: node_js
node_js:
- '0.10'
sudo: false
before_install: npm install -g grunt-cli
before_script: grunt build --verbose
deploy:
  provider: releases
  api_key:
    secure: PbeHwM34muUp/D+g9gbpBj/ABYtKRmPkgRpvSMl8zxFw/slFEoepA25komkh4QO1VGV5xGtUiIz8F6Rg+uhgWiid0F+GAxDjVc9NAUAeK9ONzKpo9H5f7JJrESBnEp06R6CVR/hVPN5v2UlKUJd2MoRYHKTM/GlnCY8/L+0j0bU=
  file: dist/cmv-widgets.zip
  on:
    repo: tmcgee/cmv-widgets
    tags: true
    all_branches: true
  skip_cleanup: true
notifications:
  slack:
    secure: PGsxufNYe3UrJhJnblafVeCrOjYjfVs8N6leOVCriIhxwIWpDS+whiGOpQQxZNRVN4beSgEhCbewNXHT0t3RT/Mrz4G800Gkdi+JaVADM5ZUSvAzM+02J780MSmbityVBwsHAQpn1/+cBInKQ/Yxf+G2b4f4ZDBloThrJwxLHTA=
